# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import roulette_pb2 as roulette__pb2


class RouletteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceBet = channel.unary_unary(
                '/roulette.Roulette/PlaceBet',
                request_serializer=roulette__pb2.PlaceBetRequest.SerializeToString,
                response_deserializer=roulette__pb2.StandardResponse.FromString,
                )
        self.GetState = channel.unary_unary(
                '/roulette.Roulette/GetState',
                request_serializer=roulette__pb2.EmptyRequest.SerializeToString,
                response_deserializer=roulette__pb2.StandardResponse.FromString,
                )


class RouletteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlaceBet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouletteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceBet': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBet,
                    request_deserializer=roulette__pb2.PlaceBetRequest.FromString,
                    response_serializer=roulette__pb2.StandardResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=roulette__pb2.EmptyRequest.FromString,
                    response_serializer=roulette__pb2.StandardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'roulette.Roulette', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Roulette(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlaceBet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/roulette.Roulette/PlaceBet',
            roulette__pb2.PlaceBetRequest.SerializeToString,
            roulette__pb2.StandardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/roulette.Roulette/GetState',
            roulette__pb2.EmptyRequest.SerializeToString,
            roulette__pb2.StandardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
